#!/usr/bin/env php
<?php
try {
    require __DIR__ . '/vendor/autoload.php';
    require __DIR__ . '/src/bootstrap.php';

    $app->run();

    $app->make(\Psr\Log\LoggerInterface::class)->info('Shutting down');
} catch (Throwable $e) {
    file_put_contents(__DIR__ . '/logs.log', $e->getMessage() . ': ' . $e->getTraceAsString());
}